# Generated by Django 3.2.4 on 2021-07-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Scity', models.CharField(max_length=50)),
                ('Ccity1', models.CharField(max_length=50)),
                ('Ccity2', models.CharField(max_length=50)),
                ('Ccity3', models.CharField(max_length=50)),
                ('Ccity4', models.CharField(max_length=50)),
                ('Ccity5', models.CharField(max_length=50)),
                ('Ccity6', models.CharField(max_length=50)),
                ('Ccity7', models.CharField(max_length=50)),
                ('Ccity8', models.CharField(max_length=50)),
                ('Ccity9', models.CharField(max_length=50)),
                ('Ccity10', models.CharField(max_length=50)),
                ('Ccity11', models.CharField(max_length=50)),
                ('Ccity12', models.CharField(max_length=50)),
                ('Ccity13', models.CharField(max_length=50)),
                ('Ccity14', models.CharField(max_length=50)),
                ('Ccity15', models.CharField(max_length=50)),
                ('Ccity16', models.CharField(max_length=50)),
                ('Ccity17', models.CharField(max_length=50)),
                ('Ccity18', models.CharField(max_length=50)),
                ('Ccity19', models.CharField(max_length=50)),
                ('Ccity20', models.CharField(max_length=50)),
                ('Ccity21', models.CharField(max_length=50)),
                ('Ccity22', models.CharField(max_length=50)),
                ('Ccity23', models.CharField(max_length=50)),
                ('Ccity24', models.CharField(max_length=50)),
                ('Ccity25', models.CharField(max_length=50)),
                ('Ccity26', models.CharField(max_length=50)),
                ('Ccity27', models.CharField(max_length=50)),
                ('Ccity28', models.CharField(max_length=50)),
            ],
        ),
    ]
